// 行业
export const SET_INDUSTRY_CATEGORY = 'SET_INDUSTRY_CATEGORY'
export const RESET_INDUSTRY_CATEGORY = 'RESET_INDUSTRY_CATEGORY'
export const SET_INDUSTRY_CATRGOTY_TABLE_PARAM = 'SET_INDUSTRY_CATRGOTY_TABLE_PARAM'
export const RESET_INDUSTRY_CATRGOTY_TABLE_PARAM = 'RESET_INDUSTRY_CATRGOTY_TABLE_PARAM'

// 品牌
export const SET_BRAND_CATEGORY = 'SET_BRAND_CATEGORY'
export const SET_BRAND_BRANDS = 'SET_BRAND_BRANDS'
export const RESET_BRAND_BRANDS = 'RESET_BRAND_BRANDS'
export const RESET_BRAND_CATEGORY = 'RESET_BRAND_CATEGORY'
export const SET_BRAND_SETTING = 'SET_BRAND_SETTING'
export const SET_BRAND_CATEGORY_OPTION = 'SET_BRAND_CATEGORY_OPTION'
export const RESET_BRAND_CATEGORY_OPTION = 'RESET_BRAND_CATEGORY_OPTION'
export const RESET_BRAND_SETTING = 'RESET_BRAND_SETTING'

// 系统
export const SET_SYS_COLLAPSED = 'SET_SYS_COLLAPSED'

// 用户
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USER_TYPE = 'SET_USER_TYPE'
